=== sei-hoan-nguyen/SampleCamProgram/Packages/Beckhoff.TwinCAT.HMI.OpcUa.22.0.6418/runtimes/win-x86/native/TcHmiOpcUa.Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "LocalizedText": {
      "description": "descUaLocalizedText",
      "type": "object",
      "properties": {
        "Locale": {
          "type": "integer"
        },
        "Text": {
          "type": "string"
        }
      },
      "required": [
        "Locale",
        "Text"
      ]
    },
    "QualifiedName": {
      "description": "descUaQualifiedName",
      "type": "object",
      "properties": {
        "NamespaceIndex": {
          "type": "integer"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": [
        "NamespaceIndex",
        "Name"
      ]
    },
    "namespace": {
      "description": "descNamespace",
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "endpoint": {
          "propertyOrder": 1,
          "type": "string",
          "default":"opc.tcp://127.0.0.1:4840"
        },
        "security": {
          "type": "string",
          "propertyOrder": 2,
          "optionMethod": {
            "symbol": "{domain}.Config::securitySettings"
          }
        },
        "advanced": {
          "type": "string",
          "propertyOrder": 3,
          "optionMethod": {
            "symbol": "{domain}.Config::advancedSettings"
          }
        },
        "connection": {
          "type": "string",
          "propertyOrder": 4,
          "optionMethod": {
            "symbol": "{domain}.Config::connectionSettings"
          }
        }
      },
      "required": [
        "endpoint",
        "advanced",
        "connection",
        "security"
      ]
    },
    "connection": {
      "description": "descConnection",
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "timeout": {
          "type": "string",
          "description": "descTimeout",
          "format": "timespan",
          "default": "PT10S",
          "formatMinimum": "PT0.1S",
          "formatMaximum": "PT30S"
        }
      },
      "required": [
        "timeout"
      ]
    },
    "advanced": {
      "description": "descAdvanced",
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "verticalLineReplacement": {
          "type": "string"
        },
        "asteriskReplacement": {
          "type": "string"
        },
        "percentReplacement": {
          "type": "string"
        },
        "colonReplacement": {
          "type": "string"
        },
        "doublePointReplacement": {
          "type": "string"
        },
        "arrayOpenReplacement": {
          "type": "string"
        },
        "arrayCloseReplacement": {
          "type": "string"
        },
        "browseValueSubelements": {
          "type": "boolean"
        },
        "definitionNameMode": {
          "type": "integer",
          "description": "descDefinitionNameMode",
          "enum": [
            0,
            1,
            2
          ],
          "default": 0,
          "options": [
            {
              "label": "useReferenceTypesAsDefinitionNames",
              "value": 0
            },
            {
              "label": "useNodeTypesAsDefinitionNames",
              "value": 1
            },
            {
              "label": "useNodeIdsAsDefinitionNames",
              "value": 2
            }
          ]
        },
        "startPoint": {
          "type": "object",
          "description": "descStartPoint",
          "properties": {
            "identifierType": {
              "type": "integer",
              "enum": [ 0, 1, 2, 3 ],
              "default": 0,
              "options": [
                {
                  "label": "Numeric",
                  "value": 0
                },
                {
                  "label": "String",
                  "value": 1
                },
                {
                  "label": "GUID",
                  "value": 2
                },
                {
                  "label": "Binary",
                  "value": 3
                }
              ]
            },
            "namespaceIndex": {
              "type": "number"
            },
            "integerIdentifier": {
              "type": "number"
            },
            "stringIdentifier": {
              "type": "string"
            },
            "guidIdentifier": {
              "type": "string"
            },
            "binaryIdentifier": {
              "type": "string",
              "format": "base64"
            }
          },
          "default": {
            "identifierType": 0,
            "namespaceIndex": 0,
            "integerIdentifier": 85,
            "stringIdentifier": "",
            "guidIdentifier": "",
            "binaryIdentifier": ""
          }
        },
        "forbiddenReferenceNodes": {
          "type": "object",
          "description": "descForbiddenReferenceNodes",
          "properties": {
            "stringNodes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "integerNodes": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "binaryNodes": {
              "type": "array",
              "items": {
                "type": "string",
                "format": "base64"
              }
            },
            "guidNodes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "ignoreNodes": {
          "description": "descIgnoreNodes",
          "type": "object",
          "properties": {
            "stringNodes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "integerNodes": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "binaryNodes": {
              "type": "array",
              "items": {
                "type": "string",
                "format": "base64"
              }
            },
            "guidNodes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "required": [
        "arrayCloseReplacement",
        "arrayOpenReplacement",
        "browseValueSubelements",
        "doublePointReplacement",
        "colonReplacement",
        "verticalLineReplacement",
        "asteriskReplacement",
        "percentReplacement",
        "definitionNameMode",
        "ignoreNodes",
        "forbiddenReferenceNodes",
        "startPoint"
      ]
    },
    "security": {
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "acceptAllServerCertificates": {
          "type": "boolean",
          "default": true
        },
        "acceptSelfSignedCertificates": {
          "type": "boolean",
          "default": true
        },
        "securityMode": {
          "type": "integer",
          "enum": [
            1,
            2,
            3
          ],
          "default": 1,
          "options": [
            {
              "label": "none",
              "value": 1
            },
            {
              "label": "sign",
              "value": 2
            },
            {
              "label": "signAndEncrypt",
              "value": 3
            }
          ]
        },
        "policyMode": {
          "type": "string",
          "enum": [
            "http://opcfoundation.org/UA/SecurityPolicy#None",
            "http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15",
            "http://opcfoundation.org/UA/SecurityPolicy#Basic256",
            "http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256"
          ],
          "options": [
            {
              "label": "none",
              "value": "http://opcfoundation.org/UA/SecurityPolicy#None"
            },
            {
              "label": "Basic128Rsa15",
              "value": "http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15"
            },
            {
              "label": "Basic256",
              "value": "http://opcfoundation.org/UA/SecurityPolicy#Basic256"
            },
            {
              "label": "Basic256Sha256",
              "value": "http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256"
            }
          ]
        },
        "certificateTrust": {
          "type": "string",
          "format": "certificate",
          "acceptFileTypes": [ ".der" ],
          "default": ""
        },
        "clientCertificate": {
          "type": "string",
          "format": "certificate",
          "acceptFileTypes": [ ".der" ],
          "default": ""
        },
        "clientPrivatekey": {
          "type": "string",
          "format": "base64",
          "acceptFileTypes": [ ".pem" ],
          "default": ""
        },
        "useHmiServerCertificate": {
          "type": "boolean",
          "default": false
        },
        "useGlobalUaUser": {
          "type": "boolean",
          "description": "descUseGlobalUaUser",
          "default": true
        },
        "authEnabled": {
          "type": "boolean",
          "default": false
        },
        "globalUser": {
          "type": "string",
          "default": ""
        },
        "globalPassword": {
          "format": "masked",
          "type": "string",
          "default": ""
        }
      },
      "required": [
        "acceptAllServerCertificates",
        "acceptSelfSignedCertificates",
        "authEnabled",
        "certificateTrust",
        "clientCertificate",
        "clientPrivatekey",
        "globalPassword",
        "globalUser",
        "policyMode",
        "securityMode",
        "useGlobalUaUser",
        "useHmiServerCertificate"
      ]
    }
  },
  "properties": {
    "advancedSettings": {
      "description": "descAdvancedSettings",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/advanced"
      },
      "default": {
        "basic": {
          "browseValueSubelements": false,
          "doublePointReplacement": "_HMI_RESERVED_DOUBLECOLON_",
          "colonReplacement": "_HMI_RESERVED_COLON_",
          "verticalLineReplacement": "_HMI_RESERVED_VERTICALLINE_",
          "asteriskReplacement": "_HMI_RESERVED_ASTERISK_",
          "percentReplacement": "_HMI_RESERVED_PERCENT_",
          "arrayOpenReplacement": "_HMI_RESERVED_ARRAYOPEN_",
          "arrayCloseReplacement": "_HMI_RESERVED_ARRAYCLOSE_"
        }
      }
    },
    "connectionSettings": {
      "description": "descConnectionSettings",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/connection"
      },
      "default": {
        "basic": {}
      }
    },
    "namespaces": {
      "description": "descNamespaces",
      "defaultConfigurable": true,
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/namespace"
      }
    },
    "securitySettings": {
      "description": "descSecuritySettings",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/security"
      },
      "default": {
        "basic": {
          "acceptAllServerCertificates": true,
          "acceptSelfSignedCertificates": true,
          "securityMode": 1,
          "policyMode": "http://opcfoundation.org/UA/SecurityPolicy#None",
          "certificateTrust": "",
          "clientCertificate": "",
          "clientPrivatekey": "",
          "useHmiServerCertificate": false,
          "useGlobalUaUser": true,
          "globalUser": "",
          "globalPassword": ""
        }
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "namespaces",
    "connectionSettings",
    "securitySettings",
    "advancedSettings"
  ]
}

=== sei-hoan-nguyen/SampleCamProgram/ControllerHMI/Server/TcHmiOpcUa/TcHmiOpcUa.Config.default.json
{
    "advancedSettings": {
        "basic": {
            "arrayCloseReplacement": "_HMI_RESERVED_ARRAYCLOSE_",
            "arrayOpenReplacement": "_HMI_RESERVED_ARRAYOPEN_",
            "asteriskReplacement": "",
            "browseValueSubelements": false,
            "colonReplacement": "",
            "definitionNameMode": 0,
            "doublePointReplacement": "_HMI_RESERVED_DOUBLECOLON_",
            "forbiddenReferenceNodes": {
                "binaryNodes": [],
                "guidNodes": [],
                "integerNodes": [],
                "stringNodes": []
            },
            "ignoreNodes": {
                "binaryNodes": [],
                "guidNodes": [],
                "integerNodes": [],
                "stringNodes": []
            },
            "percentReplacement": "",
            "startPoint": {
                "binaryIdentifier": "",
                "guidIdentifier": "",
                "identifierType": 0,
                "integerIdentifier": 85.0,
                "namespaceIndex": 0.0,
                "stringIdentifier": ""
            },
            "verticalLineReplacement": ""
        }
    },
    "connectionSettings": {
        "basic": {
            "timeout": "PT10S"
        }
    },
    "namespaces": {},
    "securitySettings": {
        "basic": {
            "acceptAllServerCertificates": true,
            "acceptSelfSignedCertificates": true,
            "authEnabled": false,
            "certificateTrust": "",
            "clientCertificate": "",
            "clientPrivatekey": "",
            "globalPassword": "",
            "globalUser": "",
            "policyMode": "http://opcfoundation.org/UA/SecurityPolicy#None",
            "securityMode": 1,
            "useGlobalUaUser": true,
            "useHmiServerCertificate": false
        }
    }
}
